spring:
  application:
    name: MessagingService
  cloud:
    nacos:
      #server-addr: 47.115.130.44:18375
      server-addr: common-nacos-dev.magestack.cn:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.115.130.44:49152/InfiniteChat
    username: root
    password: gK3T9n%q2M@j7Z4
  redis:
    database: 0
    host: 47.115.130.44
    port: 59000
    password: e65K4t8w2
  kafka:
    bootstrap-servers:
      - 47.115.130.44:9092
    consumer:
      group-id: thousnads_word_message_all
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 8081


#logging:
#  level:
#    org:
#      springframework: DEBUG




