server:
  port: 10010
spring:
  application:
    name: gateWay
  redis:
    database: 0
    host: localhost
    port: 59000
    password: e65K4t8w2
  cloud:
    nacos:
      server-addr: localhost:18375
      username: nacos
      password: Xp4#tG7!vQ
#      server-addr: common-nacos-dev.magestack.cn:8848
    gateway:
      httpclient:
        connect-timeout: 60000 # 连接超时时间，单位毫秒
        response-timeout: 60000 # 响应超时时间，单位毫秒
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:10010"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 36000
      routes:
        - id: AuthenticationService
          uri: lb://AuthenticationService
          predicates:
            - Path=/api/v1/user/**
        - id: MessagingService
          uri: lb://MessagingService
          predicates:
            - Path=/api/v1/chat/**
        - id: RealTimeCommunicationService
          uri: lb://RealTimeCommunicationService
          predicates:
            - Path=/api/v1/message/**
        - id: ContactService
          uri: lb://ContactService
          predicates:
            - Path=/api/v1/contact/**
        - id: OfflineDataStore
          uri: lb://OfflineDataStore
          predicates:
            - Path=/api/v1/offline/**
        - id: MomentService
          uri: lb://MomentService
          predicates:
            - Path=/api/v1/moment/**
